export interface HistoryRequest{
    id?:number,
    email:string,
    bookingDate?: Date,
    bookingTime?: string,
    pickupAddress: string,
    landMark: string,
    fromPlace?:number,
    toPlace?:number,
    pickupDate?: Date,
    pickupTime: string,
    cabTypeId?: number,
    contactNo: string,
    feedback: string,
    comp_time: string,
    charge?: number,
}